name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      - run: go build ./cmd/pgbranchd
      - name: Build Docker image
        run: docker build -t pg-on-zfs -f docker/Dockerfile .
