name: ci
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile
          push: false
          tags: pg-on-zfs:test
      - name: Run container tests
        run: |
          mkdir -p hostdata
          docker run -d --name pg-test --privileged -v ${GITHUB_WORKSPACE}/hostdata:/hostdata pg-on-zfs:test
          ./test.sh pg-test
          docker rm -f pg-test
