name: ci
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile
          load: true
          tags: pg-on-zfs:test
          push: false
      - run: docker run -d --name pgtest --privileged pg-on-zfs:test
      - run: ./test.sh pgtest
